import type { Company, Review, Job } from "./types";

// All data below is synthetic and for demo purposes only.
// Wording follows the platform's legally-cautious style guidelines.

function review(partial: Partial<Review> & Pick<Review, "id" | "companySlug" | "companyName" | "type" | "city" | "roleCategory" | "year" | "text">): Review {
  return {
    verified: false,
    salaryMatch: "unknown",
    officialEmployment: "unknown",
    bookingPromised: "not_applicable",
    bookingReceived: "unknown",
    internshipPaid: "no_internship",
    paymentDelay: "unknown",
    ratings: { salary: 3, schedule: 3, management: 3, conditions: 3, honesty: 3 },
    badges: [],
    status: "published",
    ...partial,
  };
}

function job(partial: Job): Job {
  return partial;
}

export const COMPANIES: Company[] = [
  {
    id: "1",
    slug: "nova-poshta",
    name: "Нова Пошта",
    city: "Київ",
    industry: "Логістика і доставка",
    trustScore: 78,
    bookingScore: 64,
    reviewsCount: 42,
    verifiedReviewsCount: 11,
    salaryMatchPercent: 82,
    officialEmploymentPercent: 90,
    bookingConfirmedPercent: 64,
    internshipPaidPercent: 70,
    paymentDelayRisk: "low",
    riskLevel: "low",
    shortSummary:
      "Велика логістична компанія з офіційним оформленням у більшості відгуків. Частина користувачів зазначає залежність доходу від навантаження.",
    pros: ["Офіційне оформлення згадується часто", "Виплати переважно вчасно", "Структуровані процеси"],
    cons: ["Високе навантаження у пік сезону", "Дохід залежить від кількості відправлень"],
    bookingSummary:
      "Бронювання заявляють і частина користувачів зазначає, що його реально оформлювали. Умови варто уточнити для конкретної позиції.",
    salarySummary:
      "Зарплата переважно збігається з вакансією. Частина користувачів зазначає, що фактичний дохід залежить від навантаження та змін.",
    employmentSummary: "Здебільшого офіційне оформлення з перших днів роботи.",
    internshipSummary: "Стажування здебільшого оплачуване, але умови різняться за регіонами.",
    interviewQuestions: [
      "З якого дня офіційне оформлення на цій позиції?",
      "Як саме формується дохід — ставка чи відрядна частина?",
      "Коли подають на бронювання і через який сервіс?",
      "Який реальний графік у пік сезону?",
      "Чи оплачується період навчання?",
    ],
    jobs: [
      job({
        id: "j1-1",
        title: "Оператор відділення",
        city: "Київ",
        salary: "18 000 – 24 000 грн",
        source: "work.ua",
        sourceUrl: "#",
        riskLevel: "low",
        bookingClaimed: true,
        shortDescription: "Робота на відділенні, офіційне оформлення, графік змінний.",
      }),
      job({
        id: "j1-2",
        title: "Водій-експедитор",
        city: "Київ",
        salary: "25 000 – 45 000 грн",
        source: "robota.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: true,
        shortDescription: "Доставка відправлень, широкий діапазон зарплати.",
      }),
    ],
    reviews: [
      review({
        id: "rv1-1",
        companySlug: "nova-poshta",
        companyName: "Нова Пошта",
        type: "employee",
        city: "Київ",
        roleCategory: "Оператор відділення",
        year: 2024,
        verified: true,
        text: "Оформлення офіційне з першого тижня. Виплати приходили вчасно. У пік сезону навантаження велике, але графік був зрозумілий заздалегідь.",
        salaryMatch: "yes",
        officialEmployment: "official_day_one",
        bookingPromised: "yes",
        bookingReceived: "yes",
        internshipPaid: "yes",
        paymentDelay: "no",
        ratings: { salary: 4, schedule: 3, management: 4, conditions: 4, honesty: 4 },
        badges: ["оформлення з першого дня", "бронювання оформили"],
      }),
      review({
        id: "rv1-2",
        companySlug: "nova-poshta",
        companyName: "Нова Пошта",
        type: "interview",
        city: "Львів",
        roleCategory: "Водій-експедитор",
        year: 2024,
        text: "На співбесіді чесно розповіли про навантаження. Зарплату пояснили як ставку плюс відрядну частину. Бронювання обіцяли після випробувального терміну.",
        salaryMatch: "partial",
        bookingPromised: "yes",
        bookingReceived: "promised_later",
        bookingTiming: "after_probation",
        ratings: { salary: 3, schedule: 3, management: 4, conditions: 3, honesty: 4 },
        badges: ["бронювання обіцяли", "зарплата частково збіглась"],
      }),
    ],
  },
  {
    id: "2",
    slug: "atb",
    name: "АТБ",
    city: "Дніпро",
    industry: "Роздрібна торгівля",
    trustScore: 61,
    bookingScore: 42,
    reviewsCount: 58,
    verifiedReviewsCount: 9,
    salaryMatchPercent: 68,
    officialEmploymentPercent: 85,
    bookingConfirmedPercent: 42,
    internshipPaidPercent: 60,
    paymentDelayRisk: "low",
    riskLevel: "medium",
    shortSummary:
      "Велика мережа магазинів. Офіційне оформлення згадується часто, проте частина користувачів зазначає високе навантаження та плинність.",
    pros: ["Офіційне оформлення", "Стабільні виплати"],
    cons: ["Високе фізичне навантаження", "Дохід залежить від переробок"],
    bookingSummary:
      "Дані про бронювання неоднорідні: частина користувачів зазначає, що його оформлювали, частина — що лише обіцяли. Потребує уточнення.",
    salarySummary:
      "Зарплата частково збігається з вакансією. Частина користувачів зазначає вплив переробок на фактичний дохід.",
    employmentSummary: "Переважно офіційне оформлення, але дата інколи відкладається до завершення навчання.",
    internshipSummary: "Стажування інколи оплачуване частково — варто уточнити заздалегідь.",
    interviewQuestions: [
      "З якого дня офіційне оформлення?",
      "Чи входять переробки в зарплату чи оплачуються окремо?",
      "Які реальні зміни та графік?",
      "Чи подають на бронювання і коли?",
      "Чи оплачується період навчання?",
    ],
    jobs: [
      job({
        id: "j2-1",
        title: "Продавець-консультант",
        city: "Дніпро",
        salary: "16 000 – 22 000 грн",
        source: "work.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: false,
        shortDescription: "Робота в торговому залі, змінний графік.",
      }),
    ],
    reviews: [
      review({
        id: "rv2-1",
        companySlug: "atb",
        companyName: "АТБ",
        type: "employee",
        city: "Дніпро",
        roleCategory: "Продавець-консультант",
        year: 2023,
        verified: true,
        text: "Оформлення офіційне, але почалося лише після двох тижнів навчання. Виплати без затримок. Навантаження високе, особливо у вихідні.",
        salaryMatch: "partial",
        officialEmployment: "after_internship",
        bookingReceived: "no",
        internshipPaid: "partial",
        paymentDelay: "no",
        ratings: { salary: 3, schedule: 2, management: 3, conditions: 3, honesty: 3 },
        badges: ["оформлення після стажування"],
      }),
    ],
  },
  {
    id: "3",
    slug: "silpo",
    name: "Сільпо",
    city: "Київ",
    industry: "Роздрібна торгівля",
    trustScore: 72,
    bookingScore: 55,
    reviewsCount: 37,
    verifiedReviewsCount: 8,
    salaryMatchPercent: 75,
    officialEmploymentPercent: 88,
    bookingConfirmedPercent: 55,
    internshipPaidPercent: 72,
    paymentDelayRisk: "low",
    riskLevel: "low",
    shortSummary:
      "Мережа супермаркетів із переважно офіційним оформленням. Частина користувачів позитивно відгукується про умови та колектив.",
    pros: ["Офіційне оформлення", "Зрозумілі процеси", "Оплачуване навчання"],
    cons: ["Дохід без бонусів невисокий", "Залежність від локації магазину"],
    bookingSummary:
      "Бронювання частково підтверджено відгуками. Умови варіюються за позиціями та регіонами.",
    salarySummary: "Зарплата переважно збігається з вакансією, бонусна частина залежить від показників магазину.",
    employmentSummary: "Здебільшого офіційне оформлення, інколи після короткого навчання.",
    internshipSummary: "Навчання переважно оплачуване.",
    interviewQuestions: [
      "З якого дня офіційне оформлення?",
      "Як формується бонусна частина?",
      "Чи подають на бронювання і коли?",
      "Який графік на цій позиції?",
      "Чи оплачується навчання?",
    ],
    jobs: [
      job({
        id: "j3-1",
        title: "Касир",
        city: "Київ",
        salary: "17 000 – 21 000 грн",
        source: "robota.ua",
        sourceUrl: "#",
        riskLevel: "low",
        bookingClaimed: true,
        shortDescription: "Робота на касі, офіційне оформлення.",
      }),
    ],
    reviews: [
      review({
        id: "rv3-1",
        companySlug: "silpo",
        companyName: "Сільпо",
        type: "employee",
        city: "Київ",
        roleCategory: "Касир",
        year: 2024,
        verified: true,
        text: "Навчання оплачували, оформили офіційно через тиждень. Графік зручний, виплати вчасно. Бронювання оформили після випробувального.",
        salaryMatch: "yes",
        officialEmployment: "official_day_one",
        bookingPromised: "yes",
        bookingReceived: "yes",
        bookingTiming: "after_probation",
        internshipPaid: "yes",
        paymentDelay: "no",
        ratings: { salary: 4, schedule: 4, management: 4, conditions: 4, honesty: 4 },
        badges: ["оформлення з першого дня", "бронювання оформили"],
      }),
    ],
  },
  {
    id: "4",
    slug: "eva",
    name: "EVA",
    city: "Дніпро",
    industry: "Аптеки і медицина",
    trustScore: 66,
    bookingScore: 38,
    reviewsCount: 29,
    verifiedReviewsCount: 6,
    salaryMatchPercent: 70,
    officialEmploymentPercent: 80,
    bookingConfirmedPercent: 38,
    internshipPaidPercent: 55,
    paymentDelayRisk: "low",
    riskLevel: "medium",
    shortSummary:
      "Мережа магазинів краси та здоров'я. Дані про бронювання обмежені, частина відгуків позитивна щодо колективу.",
    pros: ["Офіційне оформлення", "Дружній колектив у відгуках"],
    cons: ["Невисока базова ставка", "Дані про бронювання недостатні"],
    bookingSummary: "Бронювання згадується нечасто, підтверджених даних небагато. Потребує уточнення.",
    salarySummary: "Зарплата частково збігається з вакансією, відчутна бонусна частина.",
    employmentSummary: "Переважно офіційне оформлення, інколи після випробувального терміну.",
    internshipSummary: "Стажування частково оплачуване — варто уточнити.",
    interviewQuestions: [
      "З якого дня офіційне оформлення?",
      "Яка фіксована ставка без бонусів?",
      "Чи подають на бронювання?",
      "Який графік змін?",
      "Чи оплачується стажування?",
    ],
    jobs: [
      job({
        id: "j4-1",
        title: "Продавець-консультант",
        city: "Дніпро",
        salary: "15 000 – 20 000 грн",
        source: "work.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: false,
        shortDescription: "Робота в магазині, бонуси за продажі.",
      }),
    ],
    reviews: [
      review({
        id: "rv4-1",
        companySlug: "eva",
        companyName: "EVA",
        type: "applicant",
        city: "Дніпро",
        roleCategory: "Продавець-консультант",
        year: 2024,
        text: "Відгукувалася, на співбесіді про бронювання чіткої відповіді не дали. Ставка невисока, основний дохід — бонуси за продажі.",
        salaryMatch: "partial",
        bookingPromised: "no",
        bookingReceived: "not_applicable",
        ratings: { salary: 3, schedule: 3, management: 3, conditions: 3, honesty: 3 },
        badges: ["зарплата частково збіглась"],
      }),
    ],
  },
  {
    id: "5",
    slug: "rozetka",
    name: "Rozetka",
    city: "Київ",
    industry: "E-commerce",
    trustScore: 74,
    bookingScore: 60,
    reviewsCount: 45,
    verifiedReviewsCount: 12,
    salaryMatchPercent: 78,
    officialEmploymentPercent: 86,
    bookingConfirmedPercent: 60,
    internshipPaidPercent: 75,
    paymentDelayRisk: "low",
    riskLevel: "low",
    shortSummary:
      "Великий онлайн-рітейлер. Офіційне оформлення згадується часто, частина користувачів підтверджує оформлення бронювання.",
    pros: ["Офіційне оформлення", "Виплати вчасно", "Бронювання підтверджують частіше"],
    cons: ["Високий темп роботи у складських позиціях"],
    bookingSummary: "Бронювання підтверджено частиною відгуків. Умови залежать від позиції.",
    salarySummary: "Зарплата переважно збігається з вакансією.",
    employmentSummary: "Переважно офіційне оформлення з перших днів.",
    internshipSummary: "Навчання переважно оплачуване.",
    interviewQuestions: [
      "З якого дня офіційне оформлення?",
      "Коли подають на бронювання і через який сервіс?",
      "Яка структура доходу?",
      "Який реальний графік?",
      "Чи оплачується навчання?",
    ],
    jobs: [
      job({
        id: "j5-1",
        title: "Менеджер з продажу",
        city: "Київ",
        salary: "22 000 – 35 000 грн",
        source: "robota.ua",
        sourceUrl: "#",
        riskLevel: "low",
        bookingClaimed: true,
        shortDescription: "Робота з клієнтами, ставка плюс бонуси.",
      }),
    ],
    reviews: [
      review({
        id: "rv5-1",
        companySlug: "rozetka",
        companyName: "Rozetka",
        type: "employee",
        city: "Київ",
        roleCategory: "Менеджер з продажу",
        year: 2024,
        verified: true,
        text: "Оформили офіційно одразу. Бронювання подали після місяця роботи, підтвердили через Резерв+. Виплати без затримок.",
        salaryMatch: "yes",
        officialEmployment: "official_day_one",
        bookingPromised: "yes",
        bookingReceived: "yes",
        bookingTiming: "after_probation",
        internshipPaid: "yes",
        paymentDelay: "no",
        ratings: { salary: 4, schedule: 4, management: 4, conditions: 4, honesty: 5 },
        badges: ["оформлення з першого дня", "бронювання оформили"],
      }),
    ],
  },
  {
    id: "6",
    slug: "ukrposhta",
    name: "Укрпошта",
    city: "Київ",
    industry: "Логістика і доставка",
    trustScore: 58,
    bookingScore: 48,
    reviewsCount: 33,
    verifiedReviewsCount: 7,
    salaryMatchPercent: 62,
    officialEmploymentPercent: 92,
    bookingConfirmedPercent: 48,
    internshipPaidPercent: 50,
    paymentDelayRisk: "medium",
    riskLevel: "medium",
    shortSummary:
      "Державний оператор. Офіційне оформлення майже завжди, проте частина користувачів зазначає невисокі ставки та окремі затримки.",
    pros: ["Майже завжди офіційне оформлення", "Стабільна зайнятість"],
    cons: ["Невисока базова ставка", "Окремі згадки про затримки"],
    bookingSummary: "Бронювання частково підтверджено. Процедури можуть відрізнятися за регіонами.",
    salarySummary: "Зарплата інколи нижча за очікувану з вакансії. Частина користувачів зазначає залежність від регіону.",
    employmentSummary: "Офіційне оформлення майже завжди.",
    internshipSummary: "Навчання інколи неоплачуване — варто уточнити.",
    interviewQuestions: [
      "Яка фактична ставка на цій позиції?",
      "Чи бувають затримки виплат?",
      "З якого дня офіційне оформлення?",
      "Чи подають на бронювання?",
      "Чи оплачується навчання?",
    ],
    jobs: [
      job({
        id: "j6-1",
        title: "Оператор поштового зв'язку",
        city: "Київ",
        salary: "14 000 – 18 000 грн",
        source: "work.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: true,
        shortDescription: "Робота на відділенні, офіційне оформлення.",
      }),
    ],
    reviews: [
      review({
        id: "rv6-1",
        companySlug: "ukrposhta",
        companyName: "Укрпошта",
        type: "employee",
        city: "Полтава",
        roleCategory: "Оператор",
        year: 2023,
        verified: true,
        text: "Оформлення офіційне, все за КЗпП. Але ставка невисока, а одного разу виплата затрималася на кілька днів. Бронювання оформлювали довго.",
        salaryMatch: "no",
        officialEmployment: "official_day_one",
        bookingReceived: "promised_later",
        internshipPaid: "no",
        paymentDelay: "yes",
        ratings: { salary: 2, schedule: 3, management: 3, conditions: 3, honesty: 3 },
        badges: ["оформлення з першого дня", "стажування не оплачували"],
      }),
    ],
  },
  {
    id: "7",
    slug: "varus",
    name: "Varus",
    city: "Дніпро",
    industry: "Роздрібна торгівля",
    trustScore: 64,
    bookingScore: 40,
    reviewsCount: 21,
    verifiedReviewsCount: 4,
    salaryMatchPercent: 69,
    officialEmploymentPercent: 82,
    bookingConfirmedPercent: 40,
    internshipPaidPercent: 58,
    paymentDelayRisk: "low",
    riskLevel: "medium",
    shortSummary:
      "Регіональна мережа супермаркетів. Даних поки небагато, частина відгуків позитивна щодо оформлення.",
    pros: ["Офіційне оформлення згадується часто"],
    cons: ["Недостатньо підтверджених даних про бронювання"],
    bookingSummary: "Недостатньо даних про бронювання. Варто уточнити перед працевлаштуванням.",
    salarySummary: "Зарплата частково збігається з вакансією.",
    employmentSummary: "Переважно офіційне оформлення.",
    internshipSummary: "Дані про стажування обмежені.",
    interviewQuestions: [
      "З якого дня офіційне оформлення?",
      "Чи подають на бронювання?",
      "Яка структура доходу?",
      "Який графік?",
      "Чи оплачується навчання?",
    ],
    jobs: [
      job({
        id: "j7-1",
        title: "Працівник торгового залу",
        city: "Дніпро",
        salary: "16 000 – 20 000 грн",
        source: "work.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: false,
        shortDescription: "Викладка товару, робота в залі.",
      }),
    ],
    reviews: [
      review({
        id: "rv7-1",
        companySlug: "varus",
        companyName: "Varus",
        type: "interview",
        city: "Дніпро",
        roleCategory: "Працівник залу",
        year: 2024,
        text: "На співбесіді сказали, що оформлення офіційне. Про бронювання чіткої відповіді не було — обіцяли уточнити пізніше.",
        salaryMatch: "unknown",
        bookingPromised: "no",
        bookingReceived: "unknown",
        ratings: { salary: 3, schedule: 3, management: 3, conditions: 3, honesty: 3 },
        badges: [],
      }),
    ],
  },
  {
    id: "8",
    slug: "comfy",
    name: "Comfy",
    city: "Київ",
    industry: "E-commerce",
    trustScore: 70,
    bookingScore: 52,
    reviewsCount: 26,
    verifiedReviewsCount: 6,
    salaryMatchPercent: 73,
    officialEmploymentPercent: 84,
    bookingConfirmedPercent: 52,
    internshipPaidPercent: 65,
    paymentDelayRisk: "low",
    riskLevel: "low",
    shortSummary:
      "Мережа магазинів електроніки. Офіційне оформлення згадується часто, дохід суттєво залежить від бонусів за продажі.",
    pros: ["Офіційне оформлення", "Прозора бонусна система у відгуках"],
    cons: ["Дохід сильно залежить від продажів", "План продажів буває високим"],
    bookingSummary: "Бронювання частково підтверджено відгуками.",
    salarySummary:
      "Частина користувачів зазначає, що фактичний дохід залежить від бонусів за продажі та виконання плану.",
    employmentSummary: "Переважно офіційне оформлення.",
    internshipSummary: "Навчання переважно оплачуване.",
    interviewQuestions: [
      "Яка фіксована ставка без бонусів?",
      "Як формується бонусна частина і наскільки реальний план?",
      "З якого дня офіційне оформлення?",
      "Чи подають на бронювання?",
      "Чи оплачується навчання?",
    ],
    jobs: [
      job({
        id: "j8-1",
        title: "Продавець-консультант електроніки",
        city: "Київ",
        salary: "18 000 – 40 000 грн",
        source: "robota.ua",
        sourceUrl: "#",
        riskLevel: "medium",
        bookingClaimed: true,
        shortDescription: "Продажі техніки, ставка плюс бонуси, широкий діапазон доходу.",
      }),
    ],
    reviews: [
      review({
        id: "rv8-1",
        companySlug: "comfy",
        companyName: "Comfy",
        type: "employee",
        city: "Київ",
        roleCategory: "Продавець-консультант",
        year: 2024,
        verified: true,
        text: "Оформили офіційно, навчання оплатили. Дохід дуже залежить від продажів — верхня цифра з вакансії реальна лише у хороший місяць. Бронювання оформили.",
        salaryMatch: "partial",
        officialEmployment: "official_day_one",
        bookingPromised: "yes",
        bookingReceived: "yes",
        internshipPaid: "yes",
        paymentDelay: "no",
        ratings: { salary: 3, schedule: 4, management: 4, conditions: 4, honesty: 4 },
        badges: ["оформлення з першого дня", "бронювання оформили", "зарплата частково збіглась"],
      }),
    ],
  },
];

export function getCompanyBySlug(slug: string): Company | undefined {
  return COMPANIES.find((c) => c.slug === slug);
}

export function getAllCities(): string[] {
  return Array.from(new Set(COMPANIES.map((c) => c.city))).sort();
}

// Map a free-typed company name to a canonical slug. If the name matches a
// known company (case-insensitive), we reuse its slug so user reviews land on
// the right company page. Otherwise we generate a transliteration-free slug.
export function resolveCompanySlug(name: string): string {
  const normalized = name.trim().toLowerCase();
  const known = COMPANIES.find((c) => c.name.toLowerCase() === normalized);
  if (known) return known.slug;
  return normalized
    .replace(/['’"]/g, "")
    .replace(/[^a-z0-9а-яіїєґ]+/giu, "-")
    .replace(/^-+|-+$/g, "");
}

export function searchCompanies(query: string): Company[] {
  const q = query.trim().toLowerCase();
  if (!q) return COMPANIES;
  return COMPANIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.industry.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q)
  );
}
