// lib/roles.ts
// Canonical role list for the /add-review autocomplete.
// Popular roles are listed first so they appear at the top when the user
// focuses the field without typing anything.

export const ROLE_SUGGESTIONS: string[] = [
  // ── Most popular (shown first in empty-state) ─────────────────────────────
  "Продавець-консультант",
  "Касир",
  "Менеджер з продажу",
  "Sales manager",
  "Оператор контакт-центру",
  "Оператор call-центру",
  "Курʼєр",
  "Водій",
  "Комірник",
  "Комплектувальник",
  "Адміністратор",
  "Бариста",
  "Офіціант",
  "Фармацевт",
  "Провізор",
  "Бухгалтер",
  "HR-менеджер",
  "Рекрутер",
  "QA engineer",
  "Frontend developer",
  "Account manager",

  // ── Рітейл ───────────────────────────────────────────────────────────────
  "Касир-продавець",
  "Продавець",
  "Старший продавець",
  "Адміністратор магазину",
  "Керуючий магазином",
  "Директор магазину",
  "Товарознавець",
  "Мерчендайзер",
  "Працівник торгового залу",
  "Завідувач відділу",
  "Оператор торгового залу",
  "Комплектувальник замовлень",
  "Приймальник товару",
  "Охоронець магазину",
  "Контролер торгового залу",
  "Консультант з продажу",
  "Консультант з косметики",
  "Консультант з техніки",
  "Продавець мобільних аксесуарів",
  "Продавець одягу",
  "Продавець взуття",
  "Продавець продуктів",

  // ── Логістика і доставка ─────────────────────────────────────────────────
  "Курʼєр піший",
  "Курʼєр на авто",
  "Курʼєр на велосипеді",
  "Водій категорії B",
  "Водій категорії C",
  "Водій-експедитор",
  "Експедитор",
  "Оператор відділення",
  "Оператор поштового відділення",
  "Оператор доставки",
  "Вантажник",
  "Сортувальник",
  "Пакувальник",
  "Працівник складу",
  "Завідувач складу",
  "Логіст",
  "Диспетчер",
  "Менеджер з логістики",
  "Координатор доставки",
  "Керівник зміни складу",
  "Сканувальник товару",
  "Оператор WMS",

  // ── Продажі / sales ───────────────────────────────────────────────────────
  "B2B sales manager",
  "B2C sales manager",
  "Key account manager",
  "Менеджер по роботі з клієнтами",
  "Менеджер з розвитку клієнтів",
  "Менеджер з активних продажів",
  "Менеджер з холодних продажів",
  "Менеджер з телефонних продажів",
  "Менеджер з онлайн-продажів",
  "Менеджер інтернет-магазину",
  "Менеджер з роздрібних продажів",
  "Менеджер з корпоративних продажів",
  "Менеджер з тендерних продажів",
  "Торговий представник",
  "Медичний представник",
  "Регіональний менеджер",
  "Територіальний менеджер",
  "Супервайзер торгової команди",
  "Керівник відділу продажів",
  "Директор з продажів",
  "Комерційний директор",
  "Менеджер з продажу нерухомості",
  "Рієлтор",
  "Агент з нерухомості",
  "Менеджер з продажу авто",
  "Автоменеджер",
  "Менеджер автосалону",
  "Страховий агент",
  "Фінансовий консультант",
  "Кредитний менеджер",
  "Менеджер з продажу банківських продуктів",
  "Оператор продажів",
  "Консультант контакт-центру",
  "Спеціаліст з утримання клієнтів",
  "Retention manager",
  "Customer success manager",
  "Менеджер з партнерств",
  "Partnership manager",
  "Бізнес-девелопер",
  "Business development manager",
  "Lead generation manager",
  "SDR",
  "Sales development representative",
  "Pre-sale manager",

  // ── Банки і фінанси ───────────────────────────────────────────────────────
  "Клієнтський менеджер",
  "Кредитний спеціаліст",
  "Касир банку",
  "Оператор банківського відділення",
  "Спеціаліст з обслуговування клієнтів",
  "Спеціаліст підтримки банку",
  "Аналітик",
  "Фінансовий аналітик",
  "Ризик-аналітик",
  "Головний бухгалтер",
  "Економіст",
  "Спеціаліст з верифікації",
  "Спеціаліст з кредитування",
  "Спеціаліст з платежів",
  "Оператор фінансового моніторингу",

  // ── Підтримка клієнтів / call center ──────────────────────────────────────
  "Customer support specialist",
  "Support specialist",
  "Оператор чату",
  "Оператор гарячої лінії",
  "Менеджер підтримки",
  "Координатор підтримки",
  "Супервайзер контакт-центру",
  "Team lead підтримки",
  "Спеціаліст з обробки звернень",

  // ── Аптеки і медицина ─────────────────────────────────────────────────────
  "Асистент фармацевта",
  "Завідувач аптеки",
  "Адміністратор клініки",
  "Реєстратор",
  "Медичний реєстратор",
  "Медсестра",
  "Медбрат",
  "Лаборант",
  "Лікар",
  "Асистент лікаря",
  "Стоматолог-асистент",
  "Менеджер медичного центру",
  "Координатор пацієнтів",
  "Оператор медичного контакт-центру",
  "Молодший медичний персонал",

  // ── HoReCa / ресторани ────────────────────────────────────────────────────
  "Бармен",
  "Кухар",
  "Су-шеф",
  "Шеф-кухар",
  "Помічник кухаря",
  "Пекар",
  "Кондитер",
  "Адміністратор ресторану",
  "Керуючий рестораном",
  "Хостес",
  "Касир ресторану",
  "Курʼєр доставки",
  "Піцайоло",
  "Сушист",
  "Заготівельник",
  "Мийник посуду",
  "Клінер",
  "Прибиральник",
  "Працівник кухні",
  "Працівник залу",

  // ── E-commerce ────────────────────────────────────────────────────────────
  "Контент-менеджер",
  "Категорійний менеджер",
  "Оператор інтернет-магазину",
  "Менеджер маркетплейсу",
  "Спеціаліст з обробки замовлень",
  "Спеціаліст з повернень",
  "Менеджер по роботі з постачальниками",
  "Адміністратор сайту",
  "Product content specialist",
  "Marketplace manager",

  // ── IT / digital ──────────────────────────────────────────────────────────
  "Розробник",
  "Backend developer",
  "Fullstack developer",
  "Manual QA engineer",
  "Automation QA engineer",
  "Project manager",
  "Product manager",
  "Product owner",
  "UI/UX designer",
  "UX researcher",
  "Web designer",
  "Graphic designer",
  "Support engineer",
  "DevOps engineer",
  "System administrator",
  "Data analyst",
  "Business analyst",
  "SEO specialist",
  "PPC specialist",
  "SMM-менеджер",
  "Digital marketer",
  "Email marketing specialist",
  "Copywriter",
  "Technical writer",
  "Junior developer",
  "Junior QA engineer",
  "Intern developer",
  "Intern QA engineer",

  // ── Виробництво ───────────────────────────────────────────────────────────
  "Робітник виробництва",
  "Оператор виробничої лінії",
  "Слюсар-ремонтник",
  "Електромонтер",
  "Електрогазозварник",
  "Машиніст крана",
  "Водій навантажувача",
  "Оператор станка",
  "Оператор ЧПУ",
  "Складальник",
  "Майстер зміни",
  "Майстер виробництва",
  "Технолог",
  "Інженер-технолог",
  "Контролер якості",
  "Інженер з якості",
  "Слюсар",
  "Електрик",
  "Зварювальник",
  "Механік",
  "Налагоджувальник",
  "Швачка",
  "Закрійник",
  "Різноробочий",
  "Підсобний працівник",
  "Фасувальник",
  "Оператор пакувальної лінії",

  // ── Агро ──────────────────────────────────────────────────────────────────
  "Агроном",
  "Тракторист",
  "Механізатор",
  "Оператор елеватора",
  "Працівник ферми",
  "Ветеринар",
  "Зоотехнік",
  "Комірник агро",
  "Лаборант агро",
  "Сезонний працівник",
  "Водій сільгосптехніки",

  // ── Охорона ───────────────────────────────────────────────────────────────
  "Охоронець",
  "Інспектор охорони",
  "Старший зміни охорони",
  "Оператор відеоспостереження",
  "Контролер",
  "Охоронець офісу",
  "Охоронець складу",
  "Співробітник служби безпеки",
  "Начальник охорони",

  // ── Освіта ────────────────────────────────────────────────────────────────
  "Вчитель",
  "Викладач",
  "Репетитор",
  "Методист",
  "Адміністратор школи",
  "Куратор курсу",
  "Тренер",
  "Вихователь",
  "Асистент вчителя",
  "Менеджер освітніх програм",
  "Координатор навчання",
  "Ментор",
  "Карʼєрний консультант",

  // ── Адміністративні посади ────────────────────────────────────────────────
  "Офіс-менеджер",
  "Секретар",
  "Асистент керівника",
  "Помічник керівника",
  "Координатор",
  "Менеджер",
  "Керівник відділу",
  "Операційний менеджер",
  "Адміністратор рецепції",
  "Ресепшіоніст",
  "Документознавець",
  "Діловод",
  "Архіваріус",

  // ── HR / рекрутинг ────────────────────────────────────────────────────────
  "IT-рекрутер",
  "HR generalist",
  "HR business partner",
  "People partner",
  "Спеціаліст з кадрів",
  "Інспектор з кадрів",
  "Менеджер з навчання",
  "Менеджер з адаптації",
  "Employer brand manager",

  // ── Маркетинг ─────────────────────────────────────────────────────────────
  "Маркетолог",
  "Brand manager",
  "PR manager",
  "Event manager",
  "Trade marketing manager",
  "Marketing manager",

  // ── Авто / сервіс ─────────────────────────────────────────────────────────
  "Майстер-приймальник",
  "Сервісний консультант",
  "Автомеханік",
  "Автослюсар",
  "Автоелектрик",
  "Діагност",
  "Маляр",
  "Рихтувальник",
  "Шиномонтажник",
  "Мийник авто",
  "Детейлер",
  "Комірник автозапчастин",
  "Менеджер з продажу автозапчастин",

  // ── Будівництво / нерухомість ──────────────────────────────────────────────
  "Будівельник",
  "Різноробочий на будівництві",
  "Майстер будівельних робіт",
  "Прораб",
  "Інженер-будівельник",
  "Архітектор",
  "Дизайнер інтерʼєру",
  "Менеджер відділу продажів ЖК",
  "Кошторисник",
  "Геодезист",

  // ── Стажування / junior roles ─────────────────────────────────────────────
  "Стажер",
  "Практикант",
  "Junior specialist",
  "Junior manager",
  "Junior sales manager",
  "Junior marketer",
  "Junior recruiter",
  "Асистент",
  "Помічник",
  "Молодший спеціаліст",
  "Trainee",
];

/**
 * Search aliases: keywords (Ukrainian, English, transliteration) that should
 * surface specific roles even when the role name itself doesn't contain the query.
 *
 * Key   = role string (must match exactly what's in ROLE_SUGGESTIONS)
 * Value = additional search tokens for that role
 */
export const ROLE_SEARCH_ALIASES: Record<string, string[]> = {
  "Касир":                           ["kasyr", "cashier", "kasa", "каса"],
  "Касир-продавець":                 ["kasyr", "cashier"],
  "Касир банку":                     ["kasyr", "cashier", "bank"],
  "Касир ресторану":                 ["kasyr", "cashier"],
  "Курʼєр":                          ["kurier", "courier", "кур"],
  "Курʼєр піший":                    ["kurier", "courier"],
  "Курʼєр на авто":                  ["kurier", "courier", "car courier"],
  "Курʼєр на велосипеді":            ["kurier", "courier"],
  "Курʼєр доставки":                 ["kurier", "courier", "delivery"],
  "Водій":                           ["vodiy", "driver", "вод"],
  "Водій категорії B":               ["vodiy", "driver"],
  "Водій категорії C":               ["vodiy", "driver", "truck"],
  "Водій-експедитор":                ["vodiy", "driver", "ekspedytor"],
  "Водій сільгосптехніки":           ["vodiy", "driver", "agro"],
  "Продавець-консультант":           ["prodavets", "seller", "consultant"],
  "Продавець":                       ["prodavets", "seller"],
  "Менеджер з продажу":              ["sales", "prodazhi", "menedzher"],
  "Sales manager":                   ["sales", "менеджер з продажу", "менеджер"],
  "B2B sales manager":               ["b2b", "sales", "b2b sales"],
  "B2C sales manager":               ["b2c", "sales", "b2c sales"],
  "Account manager":                 ["account", "акаунт", "am"],
  "Key account manager":             ["key account", "kam", "акаунт"],
  "Оператор контакт-центру":         ["call center", "operator", "support", "колцентр", "кол-центр"],
  "Оператор call-центру":            ["call center", "operator", "support"],
  "Оператор відділення":             ["operator", "оператор", "відділення"],
  "Оператор поштового відділення":   ["operator", "poshta", "пошта"],
  "Customer support specialist":     ["support", "customer support", "cs"],
  "Support specialist":              ["support", "спеціаліст"],
  "Фармацевт":                       ["farmacevt", "pharmacist", "apteka", "аптека"],
  "Провізор":                        ["farmacevt", "pharmacist", "provisor", "провізор"],
  "Асистент фармацевта":             ["pharmacist", "apteka", "аптека"],
  "Рієлтор":                         ["realtor", "ріелтор", "real estate", "нерухомість"],
  "Агент з нерухомості":             ["realtor", "real estate", "agent"],
  "Менеджер з продажу нерухомості":  ["realtor", "real estate", "sales"],
  "Менеджер з продажу авто":         ["auto sales", "car sales", "автопродаж", "авто"],
  "Автоменеджер":                    ["auto sales", "car sales", "авто"],
  "Менеджер автосалону":             ["auto sales", "car sales", "авто"],
  "Страховий агент":                 ["insurance", "страхування", "agent"],
  "HR-менеджер":                     ["hr", "human resources", "кадри"],
  "Рекрутер":                        ["recruiter", "recruiting", "пошук персоналу"],
  "IT-рекрутер":                     ["recruiter", "hr", "it recruiter"],
  "HR generalist":                   ["hr", "generalist", "кадри"],
  "HR business partner":             ["hr", "hrbp", "кадри"],
  "SMM-менеджер":                    ["smm", "соцмережі", "social media"],
  "Маркетолог":                      ["marketing", "маркетинг", "marketer"],
  "Marketing manager":               ["marketing", "маркетинг"],
  "Digital marketer":                ["digital", "marketing", "маркетинг"],
  "Copywriter":                      ["copywriter", "копірайтер", "copy"],
  "Копірайтер":                      ["copywriter", "копірайтер"],
  "SEO specialist":                  ["seo", "оптимізація"],
  "PPC specialist":                  ["ppc", "google ads", "таргетолог"],
  "QA engineer":                     ["qa", "tester", "test engineer", "тестування"],
  "Manual QA engineer":              ["qa", "manual", "tester"],
  "Automation QA engineer":          ["qa", "automation", "tester", "autoqa"],
  "Frontend developer":              ["frontend", "front end", "react", "vue", "js"],
  "Backend developer":               ["backend", "back end", "nodejs", "python", "java"],
  "Fullstack developer":             ["fullstack", "full stack", "developer"],
  "Розробник":                       ["developer", "розробник", "програміст", "programmer"],
  "Junior developer":                ["junior", "dev", "developer"],
  "Intern developer":                ["intern", "стажер", "developer"],
  "Product manager":                 ["pm", "product", "продакт"],
  "Project manager":                 ["pm", "project", "проектний"],
  "DevOps engineer":                 ["devops", "ops", "infrastructure"],
  "Data analyst":                    ["data", "аналітика", "analyst"],
  "Business analyst":                ["ba", "business analyst", "аналітик"],
  "Бухгалтер":                       ["accountant", "accounting", "бух"],
  "Головний бухгалтер":              ["chief accountant", "accountant", "бух"],
  "Фінансовий аналітик":             ["financial analyst", "фінанси", "analyst"],
  "Економіст":                       ["economist", "economics", "економіка"],
  "Робітник виробництва":            ["worker", "робітник", "виробництво", "завод"],
  "Слюсар-ремонтник":               ["слюсар", "ремонт", "mechanic", "locksmith"],
  "Електромонтер":                  ["електрик", "electrician", "монтер", "електро"],
  "Електрогазозварник":             ["зварник", "зварювальник", "welder", "зварювання"],
  "Машиніст крана":                 ["кран", "машиніст", "crane operator"],
  "Водій навантажувача":            ["навантажувач", "forklift", "погрузчик"],
  "Охоронець":                       ["security", "guard", "охорона"],
  "Охоронець магазину":              ["security", "guard", "охорона"],
  "Кухар":                           ["cook", "chef", "кухня"],
  "Шеф-кухар":                       ["chef", "head chef", "кухня"],
  "Бариста":                         ["barista", "coffee", "кава"],
  "Офіціант":                        ["waiter", "server", "зала"],
  "Бармен":                          ["bartender", "bar", "бар"],
  "Стажер":                          ["intern", "trainee", "стажування"],
  "Практикант":                      ["intern", "trainee", "стажування"],
  "Trainee":                         ["intern", "стажер", "trainee"],
  "Медсестра":                       ["nurse", "медицина", "мед"],
  "Лікар":                           ["doctor", "лікар", "медицина"],
  "Адміністратор":                   ["admin", "адмін", "адміністратор"],
  "Офіс-менеджер":                   ["office manager", "офіс", "admin"],
  "Customer success manager":        ["csm", "customer success", "cs"],
  "Retention manager":               ["retention", "утримання", "cs"],
  "Business development manager":    ["bdm", "biz dev", "business development"],
};

// ── Categorised role lists for contextual autocomplete ────────────────────────

export interface RoleCategory {
  id: string;
  label: string;
  roles: string[];
}

export const ROLE_CATEGORIES: RoleCategory[] = [
  {
    id: "production",
    label: "Виробництво / завод",
    roles: [
      "Робітник виробництва",
      "Оператор виробничої лінії",
      "Слюсар-ремонтник",
      "Електромонтер",
      "Електрогазозварник",
      "Машиніст крана",
      "Водій навантажувача",
      "Токар",
      "Фрезерувальник",
      "Формувальник",
      "Контролер якості",
      "Лаборант",
      "Майстер зміни",
      "Інженер-технолог",
      "Механік",
      "Комірник",
      "Охоронник",
      "Прибиральник виробничих приміщень",
    ],
  },
  {
    id: "logistics",
    label: "Логістика / доставка",
    roles: [
      "Оператор відділення",
      "Курʼєр",
      "Водій",
      "Водій-експедитор",
      "Сортувальник",
      "Вантажник",
      "Комірник",
      "Комплектувальник",
      "Логіст",
      "Менеджер відділення",
      "Оператор контакт-центру",
      "Фахівець з приймання вантажів",
    ],
  },
  {
    id: "banking",
    label: "Банк / фінанси",
    roles: [
      "Менеджер з продажу банківських продуктів",
      "Кредитний спеціаліст",
      "Касир банку",
      "Оператор контакт-центру",
      "Фінансовий консультант",
      "Спеціаліст з обслуговування клієнтів",
      "Аналітик",
      "Ризик-менеджер",
      "Бухгалтер",
      "Юрист",
    ],
  },
  {
    id: "retail",
    label: "Ритейл / магазини",
    roles: [
      "Продавець-консультант",
      "Касир",
      "Адміністратор магазину",
      "Менеджер з продажу",
      "Товарознавець",
      "Комірник",
      "Мерчендайзер",
      "Охоронник",
      "Директор магазину",
    ],
  },
  {
    id: "office",
    label: "Офіс / адміністрація",
    roles: [
      "Офіс-менеджер",
      "Адміністратор",
      "HR-менеджер",
      "Рекрутер",
      "Бухгалтер",
      "Юрист",
      "Асистент керівника",
      "Менеджер по роботі з клієнтами",
    ],
  },
  {
    id: "it",
    label: "IT / digital",
    roles: [
      "Frontend developer",
      "Backend developer",
      "Full-stack developer",
      "QA engineer",
      "Project manager",
      "Product manager",
      "UI/UX designer",
      "Data analyst",
      "DevOps engineer",
      "Support specialist",
    ],
  },
  {
    id: "horeca",
    label: "HoReCa",
    roles: [
      "Офіціант",
      "Бариста",
      "Кухар",
      "Пекар",
      "Кондитер",
      "Адміністратор закладу",
      "Прибиральник",
      "Менеджер ресторану",
    ],
  },
  {
    id: "social",
    label: "Освіта / медицина",
    roles: [
      "Вчитель",
      "Викладач",
      "Вихователь",
      "Медсестра",
      "Лікар",
      "Фармацевт",
      "Провізор",
      "Соціальний працівник",
    ],
  },
];

// ── Context detection ─────────────────────────────────────────────────────────

const CONTEXT_RULES: Array<{ patterns: string[]; categoryId: string }> = [
  {
    categoryId: "production",
    patterns: [
      "запоріжсталь", "запорожсталь", "метінвест", "metinvest",
      "арселор", "arcelor", "інтерпайп", "interpipe",
      "феросплав", "сталь", "steel", "метал", "metal",
      "завод", "завод", "комбінат", "kombinat", "фабрик",
      "дтек", "dtek", "оболонь", "фармак", "farmak",
      "дарниця", "артеріум", "біофарма",
    ],
  },
  {
    categoryId: "logistics",
    patterns: [
      "nova-poshta", "нова пошта", "novaposhta",
      "укрпошта", "ukrposhta", "meest", "delivery",
      "bolt-food", "glovo", "логіст", "logist",
      "sat", "нічний експрес",
    ],
  },
  {
    categoryId: "banking",
    patterns: [
      "банк", "bank", "a-bank", "a-банк",
      "pryvatbank", "приватбанк", "privatbank",
      "monobank", "монобанк", "otp-bank", "otp bank",
      "raiffeisen", "райффайзен", "pumb", "пумб",
      "ощадбанк", "oshchadbank", "укрсиббанк",
      "sense-bank", "кредобанк", "kredobank",
    ],
  },
  {
    categoryId: "retail",
    patterns: [
      "atb", "атб", "silpo", "сільпо",
      "fora", "фора", "eva", "eva",
      "rozetka", "розетка", "epicentr", "епіцентр",
      "metro", "metro", "comfy", "foxtrot",
      "varus", "варус", "novus", "новус",
      "аврора", "avrora", "просто", "prostor",
    ],
  },
  {
    categoryId: "horeca",
    patterns: [
      "mcdonalds", "mcdonald", "kfc", "domino",
      "пузата хата", "mafia", "mafia", "сушия",
      "aroma", "salateira", "lviv croissants",
      "ресторан", "кафе", "кофейня",
    ],
  },
  {
    categoryId: "it",
    patterns: [
      "softserve", "epam", "globallogic", "luxoft",
      "intellias", "n-ix", "ciklum", "dataart",
      "genesis", "macpaw", "grammarly", "netpeak",
      "betterme", "preply", "jooble", "it", "digital",
    ],
  },
];

/**
 * Returns the most relevant role category IDs for a given company.
 * The matched category comes first; rest follow in original order.
 */
export function getContextualRoles(
  companyName: string,
  companySlug: string
): string[] {
  const haystack = `${companyName} ${companySlug}`.toLowerCase();

  for (const rule of CONTEXT_RULES) {
    if (rule.patterns.some((p) => haystack.includes(p))) {
      // Found a match — put that category's roles first
      const matched   = ROLE_CATEGORIES.find((c) => c.id === rule.categoryId);
      const others    = ROLE_CATEGORIES.filter((c) => c.id !== rule.categoryId);
      const allRoles  = [
        ...(matched?.roles ?? []),
        ...others.flatMap((c) => c.roles),
      ];
      // Deduplicate while preserving order
      const seen = new Set<string>();
      return allRoles.filter((r) => (seen.has(r) ? false : (seen.add(r), true)));
    }
  }

  // No context match — use default order from ROLE_SUGGESTIONS
  return ROLE_SUGGESTIONS;
}
